services:
    _defaults:
        autowire: true
        public: false

    Biig\Component\User\Jwt\Command\JwtGeneratorCommand:
        tags:
            - { name: 'console.command' }

    Biig\Component\User\Security\AuthenticatedUserProvider:
        arguments:
            $tokenStorage: '@security.token_storage'
